### PR TITLE
Update to syn 2/synstructure 0.13

### PR DESCRIPTION
**Pull request by glandium**

### CODE REVIEW

**Comment by atouchet** [comment]
@bholley @emilio Is there someone who could merge this and put out a new release? This would be useful to have for Servo too.

**Review by emilio — APPROVED** [review]

**Comment by emilio** [comment]
I don't have the permissions but this looks good to me.

**Comment by atouchet** [comment]
Thanks @emilio. Do you have access to publish 0.1.3 to crates.io?

**Comment by emilio** [comment]
Yes, done now.

**Pull request merged**
